// Positron — Test-Templates für verschiedene Frameworks

import type { TestReport } from '@positron/shared';

/**
 * Gibt ein Template für einen bestimmten Test-Framework zurück.
 */
export function getTemplate(framework: string): string {
	switch (framework) {
		case 'vitest':
			return vitestTemplate;
		case 'jest':
			return jestTemplate;
		case 'mocha':
			return mochaTemplate;
		case 'pytest':
			return pytestTemplate;
		default:
			return defaultTemplate;
	}
}

const vitestTemplate = `import { describe, expect, test } from 'vitest';

describe('smoke', () => {
  test('basic assertion', () => {
    expect(1 + 1).toBe(2);
  });
});
`;

const jestTemplate = `describe('smoke', () => {
  test('basic assertion', () => {
    expect(1 + 1).toBe(2);
  });
});
`;

const mochaTemplate = `const assert = require('assert');

describe('smoke', () => {
  it('basic assertion', () => {
    assert.strictEqual(1 + 1, 2);
  });
});
`;

const pytestTemplate = `def test_basic():
    assert 1 + 1 == 2
`;

const defaultTemplate = `# Test
# Bitte füge hier Tests für das Projekt hinzu
`;

/**
 * Rendert einen Test-Report als Markdown.
 */
export function renderTestReportMarkdown(report: TestReport): string {
	const statusEmoji = report.status === 'passed' ? '✅' : report.status === 'failed' ? '❌' : '⏭️';
	return [
		'## Test Report',
		'',
		`${statusEmoji} **Status:** ${report.status}`,
		`**Summary:** ${report.summary}`,
		`**Passed:** ${report.passed} / ${report.total}`,
		`**Failed:** ${report.failed}`,
		`**Duration:** ${report.durationMs}ms`,
		report.artifactPath ? `**Artifact:** ${report.artifactPath}` : null,
		'',
	]
		.filter(Boolean)
		.join('\n');
}

/**
 * Rendert einen Test-Report als GitHub-Kommentar.
 */
export function renderTestReportComment(report: TestReport): string {
	const statusIcon = report.status === 'passed' ? '✅' : report.status === 'failed' ? '❌' : '⏭️';
	return [
		`### ${statusIcon} Test Results`,
		'',
		'| Metric | Value |',
		'|--------|-------|',
		`| Status | ${report.status} |`,
		`| Passed | ${report.passed} |`,
		`| Failed | ${report.failed} |`,
		`| Total  | ${report.total} |`,
		`| Time   | ${report.durationMs}ms |`,
		'',
		`**${report.summary}**`,
		'',
		'_Generated by Positron Sandbox_',
	].join('\n');
}
