import { describe, it, expect } from 'vitest';
import { getTemplate, renderTestReportMarkdown, renderTestReportComment } from '../test-templates.js';
import type { TestReport } from '@positron/shared';

// ==============================
// getTemplate
// ==============================

describe('getTemplate', () => {
  it('should return vitest template', () => {
    const template = getTemplate('vitest');
    expect(template).toContain('vitest');
    expect(template).toContain('describe');
    expect(template).toContain('expect');
  });

  it('should return jest template', () => {
    const template = getTemplate('jest');
    expect(template).toContain('describe');
    expect(template).toContain('expect');
    expect(template).not.toContain('vitest');
  });

  it('should return mocha template', () => {
    const template = getTemplate('mocha');
    expect(template).toContain('assert');
    expect(template).toContain('require');
  });

  it('should return pytest template', () => {
    const template = getTemplate('pytest');
    expect(template).toContain('def test_basic');
    expect(template).toContain('assert');
  });

  it('should return default template for unknown frameworks', () => {
    const template = getTemplate('unknown');
    expect(template).toContain('# Test');
  });

  it('should return default template for empty string', () => {
    const template = getTemplate('');
    expect(template).toContain('# Test');
  });
});

// ==============================
// renderTestReportMarkdown
// ==============================

describe('renderTestReportMarkdown', () => {
  const baseReport: TestReport = {
    status: 'passed',
    summary: 'All tests passed',
    passed: 42,
    failed: 0,
    total: 42,
    durationMs: 1234,
  };

  it('should render passed report', () => {
    const md = renderTestReportMarkdown(baseReport);
    expect(md).toContain('✅');
    expect(md).toContain('**Status:** passed');
    expect(md).toContain('**Passed:** 42');
    expect(md).toContain('**Duration:** 1234ms');
  });

  it('should render failed report with ❌', () => {
    const md = renderTestReportMarkdown({ ...baseReport, status: 'failed', failed: 5 });
    expect(md).toContain('❌');
    expect(md).toContain('**Failed:** 5');
  });

  it('should render skipped report with ⏭️', () => {
    const md = renderTestReportMarkdown({ ...baseReport, status: 'skipped' });
    expect(md).toContain('⏭️');
    expect(md).toContain('**Status:** skipped');
  });

  it('should include artifact path when present', () => {
    const md = renderTestReportMarkdown({ ...baseReport, artifactPath: '/path/to/report.xml' });
    expect(md).toContain('/path/to/report.xml');
  });

  it('should not include artifact line when absent', () => {
    const md = renderTestReportMarkdown(baseReport);
    expect(md).not.toContain('**Artifact:**');
  });
});

// ==============================
// renderTestReportComment
// ==============================

describe('renderTestReportComment', () => {
  const baseReport: TestReport = {
    status: 'passed',
    summary: 'Tests passed',
    passed: 10,
    failed: 0,
    total: 10,
    durationMs: 500,
  };

  it('should render passed comment', () => {
    const comment = renderTestReportComment(baseReport);
    expect(comment).toContain('✅');
    expect(comment).toContain('| Status | passed |');
    expect(comment).toContain('| Passed | 10 |');
  });

  it('should render failed comment', () => {
    const comment = renderTestReportComment({ ...baseReport, status: 'failed', failed: 3 });
    expect(comment).toContain('❌');
    expect(comment).toContain('| Failed | 3 |');
  });

  it('should render as markdown table', () => {
    const comment = renderTestReportComment(baseReport);
    expect(comment).toContain('| Metric | Value |');
    expect(comment).toContain('|--------|-------|');
  });

  it('should include generated footer', () => {
    const comment = renderTestReportComment(baseReport);
    expect(comment).toContain('Generated by Positron Sandbox');
  });
});
