// Positron — Stage 3 Canonical Manifest
//
// SINGLE SOURCE OF TRUTH for all Stage 3 values.
// Policy, harness, tests, and docs MUST reference this manifest.
// No independent copies of these values are permitted.
//
// ALL constants below are byte-exact — no dynamic placeholders.
// The SHA-256 values are computed over the exact strings in this file.
//
// Version: 2 — 2026-07-14 (Execution-blocker remediation: fixed PR body formatting,
//   added centralized SHA-256 helpers, documented Git-blob-SHA vs canonical SHA-256.)

import crypto from 'node:crypto';

// ---------------------------------------------------------------------------
// Canonical File Content
// ---------------------------------------------------------------------------

/** Exact file content to write — NO dynamic placeholders. Byte-exact. */
export const CANONICAL_FILE_CONTENT = [
	'# Positron Stage 3 — Supervised Real Mode Pilot',
	'',
	'## Execution Metadata',
	'',
	'| Field | Value |',
	'|-------|-------|',
	'| Pilot ID | positron-stage3-pilot-001 |',
	'| Timestamp | Execution timestamp recorded in audit log |',
	'| Repository | xxammaxx/positron-sandbox |',
	'| Branch | positron/issue-308-stage3-pilot |',
	'| Mode | Supervised Single-Process Real Write |',
	'| Token Type | Fine-grained PAT |',
	'| Merge | FORBIDDEN |',
	'',
	'## Purpose',
	'',
	'This file was created by the Positron Stage 3 Supervised Real Mode Pilot.',
	'It proves that Positron can perform a strictly controlled, minimal',
	'write operation on a sandbox repository under full supervision with',
	'kill-switch protection, policy enforcement, and audit logging.',
	'',
	'## Boundaries Enforced',
	'',
	'| Boundary | Mechanism |',
	'|----------|-----------|',
	'| Single process | POSITRON_DISABLE_QUEUE=true, maxConcurrency=1 |',
	'| Single workspace | Process-scoped lock |',
	'| Single branch | Branch name from Approval Package |',
	'| Single file | This file only (stage3/positron-supervised-pilot.md) |',
	'| Single commit | maxWritesPerRun=1 |',
	'| Single draft PR | One PR, no merge |',
	'| No merge | POSITRON_MERGE_KILL_SWITCH=true |',
	'| No second write | Idempotency key enforced |',
	'',
	'## Gate Results',
	'',
	'| Gate | Result |',
	'|------|--------|',
	'| Policy gates | Recorded in audit log |',
	'| Harness gates | Recorded in audit log |',
	'| Audit sink | Recorded in audit log |',
	'| Token lifecycle | Recorded in audit log |',
	'',
	'## Stage 3 Status',
	'',
	'**STAGE3_PILOT_COMPLETED: See audit log for final status**',
	'',
	'## Next Stage',
	'',
	'Stage 4 remains BLOCKED pending:',
	'- Separate owner approval',
	'- Multi-process workspace lock resolution (Issue #324)',
	'- Full compliance and security re-review',
	'',
	'---',
	'*Generated by Positron Issue Orchestrator — Stage 3 Supervised Real Mode Pilot*',
	'',
].join('\n');

// ---------------------------------------------------------------------------
// Repository and Branch (must precede PR body which references them)
// ---------------------------------------------------------------------------

export const CANONICAL_REPOSITORY = 'xxammaxx/positron-sandbox';
export const FORBIDDEN_REPOSITORIES = ['xxammaxx/Positron'] as const;
export const CANONICAL_BASE_BRANCH = 'main';
export const CANONICAL_TARGET_BRANCH = 'positron/issue-308-stage3-pilot';
export const CANONICAL_FILE_PATH = 'stage3/positron-supervised-pilot.md';

// ---------------------------------------------------------------------------
// Canonical PR Body
// ---------------------------------------------------------------------------

/** Exact PR body — does NOT claim premature token revocation. */
export const CANONICAL_PR_BODY = [
	'## Stage 3 Supervised Real Mode Pilot — Sandbox Marker',
	'',
	'### Status: STAGE3_EXECUTING — PR Created, Pending Owner Verification',
	'',
	'This PR was created by the Positron Stage 3 Supervised Real Mode Pilot.',
	'It contains exactly one file (`stage3/positron-supervised-pilot.md`)',
	'and proves that Positron can perform a strictly controlled, minimal',
	'write operation on a sandbox repository.',
	'',
	'### Boundaries Enforced',
	'',
	'| Boundary | Status |',
	'|----------|--------|',
	'| Single process | ENFORCED |',
	'| Single workspace | ENFORCED |',
	'| Single branch | ENFORCED |',
	'| Single file | ENFORCED |',
	'| Single commit | ENFORCED |',
	'| Single draft PR | ENFORCED |',
	'| No merge | ENFORCED |',
	'',
	'### Verification',
	'',
]
	.concat([
		`- SHA-256 of file: \`${crypto.createHash('sha256').update(CANONICAL_FILE_CONTENT, 'utf8').digest('hex')}\``,
		`- File size: ${Buffer.byteLength(CANONICAL_FILE_CONTENT, 'utf8')} bytes`,
		`- Branch: \`${CANONICAL_TARGET_BRANCH}\``,
		'- No other mutations were performed',
		'',
		'### Do Not Merge',
		'',
		'This is a supervised pilot PR. Merge requires separate owner approval.',
		'The Stage 3 credential must be revoked immediately after read-only',
		'verification. Revocation is not asserted by this pull request and',
		'requires separate owner confirmation.',
		'',
		'### Related',
		'- Issue: #308 (Full Real Mode Pilot)',
		'- Approval Package: `docs/evidence/issue-308/stage3-supervised-pilot-approval-package.md`',
	])
	.join('\n');

// ---------------------------------------------------------------------------
// Canonical Commit Message
// ---------------------------------------------------------------------------

export const CANONICAL_COMMIT_MESSAGE = 'feat(issue-308): stage 3 supervised real mode pilot';

export const CANONICAL_COMMIT_BODY = [
	'- Create sandbox marker file stage3/positron-supervised-pilot.md',
	'- Prove single-process, single-branch, single-file controlled write',
	'- No merge, no production repo, no second mutation',
	'- PAT scheduled for revocation after owner verification',
].join('\n');

// ---------------------------------------------------------------------------
// Canonical PR Title
// ---------------------------------------------------------------------------

export const CANONICAL_PR_TITLE =
	'feat(issue-308): Stage 3 supervised real mode pilot — sandbox marker';

// ---------------------------------------------------------------------------
// Quantity Limits
// ---------------------------------------------------------------------------

export const MAX_BRANCHES = 1;
export const MAX_FILE_WRITES = 1;
export const MAX_COMMITS = 1;
export const MAX_PULL_REQUESTS = 1;
export const MERGE_FORBIDDEN = true as const;
export const PRODUCTION_REPOSITORY_FORBIDDEN = true as const;
export const REQUIRE_DRAFT_PR = true as const;

// ---------------------------------------------------------------------------
// Centralized SHA-256 Helpers
// ---------------------------------------------------------------------------
//
// IMPORTANT: GitHub's git blob SHA is NOT the same as canonical SHA-256.
// GitHub computes git blob SHA using `git hash-object` which prepends
// "blob <size>\0" before the content and uses SHA-1 (historically) or SHA-256
// (in new repositories). The canonical SHA-256 used by Positron is a
// plain SHA-256 hash over the exact UTF-8 bytes of the content ONLY.
//
// Source of truth: this module. All other modules and tests MUST import
// these helpers from here — no independent hash computations.

/**
 * Compute SHA-256 hex digest of a UTF-8 string.
 * This is the canonical Positron SHA-256 — plain SHA-256 over the exact bytes.
 */
export function sha256Utf8(content: string): string {
	return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

/**
 * Compute SHA-256 hex digest of raw bytes.
 */
export function sha256Bytes(content: Uint8Array): string {
	return crypto.createHash('sha256').update(content).digest('hex');
}

/**
 * Compute UTF-8 byte length of a string.
 */
export function utf8ByteLength(content: string): number {
	return Buffer.byteLength(content, 'utf8');
}

// ---------------------------------------------------------------------------
// Computed Hashes and Lengths (using centralized helpers)
// ---------------------------------------------------------------------------

/** UTF-8 byte length of CANONICAL_FILE_CONTENT. */
export const CANONICAL_FILE_LENGTH = utf8ByteLength(CANONICAL_FILE_CONTENT);

/** SHA-256 hex digest of CANONICAL_FILE_CONTENT. */
export const CANONICAL_FILE_SHA256 = sha256Utf8(CANONICAL_FILE_CONTENT);

/** SHA-256 hex digest of CANONICAL_PR_BODY. */
export const CANONICAL_PR_BODY_SHA256 = sha256Utf8(CANONICAL_PR_BODY);

/** SHA-256 hex digest of commit message + body for approval binding. */
export const CANONICAL_COMMIT_MESSAGE_SHA256 = sha256Utf8(
	CANONICAL_COMMIT_MESSAGE + '\n\n' + CANONICAL_COMMIT_BODY,
);

/** SHA-256 hex digest of PR title + body for approval binding. */
export const CANONICAL_PR_METADATA_SHA256 = sha256Utf8(
	CANONICAL_PR_TITLE + '\n' + CANONICAL_PR_BODY,
);

// ---------------------------------------------------------------------------
// Manifest (self-describing)
// ---------------------------------------------------------------------------

export const STAGE3_MANIFEST = {
	manifestVersion: 1,
	repository: CANONICAL_REPOSITORY,
	baseBranch: CANONICAL_BASE_BRANCH,
	targetBranch: CANONICAL_TARGET_BRANCH,
	filePath: CANONICAL_FILE_PATH,
	fileUtf8ByteLength: CANONICAL_FILE_LENGTH,
	fileSha256: CANONICAL_FILE_SHA256,
	commitSubject: CANONICAL_COMMIT_MESSAGE,
	commitBody: CANONICAL_COMMIT_BODY,
	prTitle: CANONICAL_PR_TITLE,
	prBody: CANONICAL_PR_BODY,
	prDraft: REQUIRE_DRAFT_PR,
	maxBranches: MAX_BRANCHES,
	maxFileWrites: MAX_FILE_WRITES,
	maxCommits: MAX_COMMITS,
	maxPullRequests: MAX_PULL_REQUESTS,
	mergeForbidden: MERGE_FORBIDDEN,
	productionRepositoryForbidden: PRODUCTION_REPOSITORY_FORBIDDEN,
} as const;

/**
 * Compute SHA-256 of the full manifest for integrity verification.
 * This allows downstream code to verify that the manifest hasn't been tampered with.
 */
export function computeManifestSha256(): string {
	const serialized = JSON.stringify(STAGE3_MANIFEST, null, 2);
	return sha256Utf8(serialized);
}
